version: "3"
services:
  learn-monbodb-replication-member-1:
    container_name: learn-mongo-member-1
    image: mongo/bionic:latest
    volumes:
     - db_data_member_1:/data/db
     - ./common_data:/data/common
    ports:
     - 27111:27017
    build: ./member_1
    restart: always

  learn-monbodb-replication-member-2:
    container_name: learn-mongo-member-2
    image: mongo/bionic:latest
    volumes:
     - db_data_member_2:/data/db
     - ./common_data:/data/common
    ports:
     - 27222:27017
    build: ./member_2
    restart: always

  learn-monbodb-replication-member-3:
    container_name: learn-mongo-member-3
    image: mongo/bionic:latest
    volumes:
     - db_data_member_3:/data/db
     - ./common_data:/data/common
    ports:
     - 27333:27017
    build: ./member_3
    restart: always

volumes:
  db_data_member_1: {}
  db_data_member_2: {}
  db_data_member_3: {}
